version: '3.9'

services:
  web:
    build:
      context: .
    command: gunicorn locallibrary.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web


volumes:
  static_volume:
